apiVersion: v1
kind: Pod
metadata:
  name: todo-app
  labels:
    project: todo-app
spec:
  containers:
    - name: todo-app
      image: subrahmanyahegde234/hegde:todo-0.0.3
      ports:
        - containerPort: 8080