spring:
  application:
    name: todo-service
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/todo_app?serverTimezone=UTC}
    username: ${JDBC_DATABASE_USERNAME:root}
    password: ${JDBC_DATABASE_PASSWORD:password}
    dbcp2:
      max-wait-millis: 30000
      validation-query: /* ping */ select 1
      validation-query-timeout: 30
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
