spring:
  application:
    name: todo-service
  datasource:
    url: jdbc:h2:mem:todo_app;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
    dbcp2:
      max-wait-millis: 30000
      validation-query: /* ping */ select 1
      validation-query-timeout: 30
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
